name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_NAME: hga-demo
jobs:
  test:
    env:
      MONGODB_ADDRESS: 127.0.0.1
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "${{ env.MONGODB_ADDRESS }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "${{ env.MONGODB_USERNAME }}"
